name: Check

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: CMake
      run: cmake . -DBUILD_TESTS=ON
    - name: Build
      run: make -j
    - name: Test
      run: make test
